### ISSUE TITLE
Suggesting Edit: Hello Holo Tutorial

### ISSUE THREAD

**Issue by simwilso** [holochain/docs-pages#104]
Page URL: http://developer.holochain.org/docs/tutorials/coreconcepts/hello_holo/

There is an issue compiling with 'hc package' in the 'Generate a Zome' section.
The config.toml file errors.
I found it works when I update the dependencies  like this:

```
[dependencies]
serde = "=1.0.89"
serde_json = { version = "=1.0.39", features = ["preserve_order"] }
serde_derive = "=1.0.89"
hdk = { git = "https://github.com/holochain/holochain-rust", tag = "v0.0.34-alpha1" }
holochain_wasm_utils = { git = "https://github.com/holochain/holochain-rust", tag = "v0.0.34-alpha1" }
holochain_json_derive = "=0.0.17"
```

**Comment by freesig** [comment]
This should be fixed in the latest holonix release. I think it's out tonight. Feel free to reopen if not.
