### ISSUE TITLE
make note of recommended process to open GH issues for troubleshooting

### ISSUE THREAD

**Issue by Connoropolous** [holochain/docs-pages#11]
do this wherever someone is installing something. 

Bonus: create an issue template

**Comment by freesig** [comment]
There is a issue template from the website now. Do you think we need a contributing guide on the github as well?

**Comment by dhtnetwork** [comment]
Yes, I think it would be helpful to have a contributing template and/or contributing protocol. It will make it easier. And I believe that is on our roadmap.
