### ISSUE TITLE
Suggesting Edit: Hello Gui Tutorial

### ISSUE THREAD

**Issue by vital-edu** [holochain/docs-pages#111]
Page URL: http://developer.holochain.org/docs/tutorials/coreconcepts/hello_gui/

In the section Run a simple server, the command 

```
python -m SimpleHTTPServer
```

is not valid anymore (it will cause the error 'No module named SimpleHTTPServer').

This command should be replaced by:

```
python -m http.server
```

**Comment by freesig** [comment]
Ah that's the python 3 way. I should specify both. I will update these.

**Comment by freesig** [comment]
Fixed in latest update
