### ISSUE TITLE
Suggesting Edit: Install Holochain

### ISSUE THREAD

**Issue by adappt-io** [holochain/docs-pages#117]
Page URL: http://developer.holochain.org/docs/install/
After running the script in Linux, it says:
"Installation finished!  To ensure that the necessary environment
variables are set, either log in again, or type

  ~/.nix-profile/etc/profile.d/nix.sh"

However, nix.sh in this location is not an executable.. the script should chmod +x nix.sh first.  And presumably the daemon version also in that directory.

**Comment by adappt-io** [comment]
Attempting the next command "nix-env" is not found.  I found it in /nix/store/6chjfy4j6hjwj5f8zcbbdg02i21x1qsi-nix-2.3.1/bin, and it works running it from there.  This was after rebooting.  Note this install is in a brand new environment (manjaro xfce), just following the steps.

**Comment by freesig** [comment]
Hi which shell are you running?
Normally that script would put the environment variables into the shell but it doesn't look like it's working for you.

**Comment by adappt-io** [comment]
I got it working.. it was missing $NIXPATH, and I found an issue entered by James Ray in January with the same behaviour (not working on Arch Linux).
