### ISSUE TITLE
Suggesting Edit: Core Concepts

### ISSUE THREAD

**Issue by Klayemore** [holochain/docs-pages#118]
Page URL: https://developer.holochain.org/docs/concepts/5_linking_data_together/
- "ukulele" is spelled incorrectly (or differently from the content) on the illustrations

Page URL: https://developer.holochain.org/docs/concepts/3_private_data/
- There is some writing here that is visible, which reads "[ diagram: maybe this following table could be made more visual? ] [color=#f60]" above the table.

**Comment by pdaoust** [comment]
point 1: oh my gosh, you're right! :O

point 2: fixed in the #91 branch :+1:

**Comment by pdaoust** [comment]
Pushed some changes for the ukulele spelling to #91 .
