### ISSUE TITLE
Suggesting Edit: Install Holochain

### ISSUE THREAD

**Issue by drewcasey88** [holochain/docs-pages#119]
Page URL: http://developer.holochain.org/docs/install/

when running `hc --version` I am receiving `hc 0.0.34-alpha1`

**Comment by dhtnetwork** [comment]
Hi @drewcasey88 that's correct. Meister explains why that is the case on this Forum [thread](https://forum.holochain.org/t/release-churn-branch-stability-and-changes-to-binary-building/1333/7). 

"you may also have noticed that https://holochain.love is pointing to an older version of binaries (i think 0.0.34)

there’s a few reasons for this: check out the Forum thread for all the reasons. HC Core is still sorting this out.  Let me know if we can close out this issue.

**Comment by drewcasey88** [comment]
@dhtnetwork sure we can close this. Just wanted to bring it to attention if it was not already known!
