### ISSUE TITLE
Review Holochain website and Holochain FAQ - update any outdated info

### ISSUE THREAD

**Issue by dhtnetwork** [holochain/docs-pages#12]
From Jimmy. He is doing a review on Holochain.  
"hmmm, any intention of updating the website? The JavaScript/Lisp section doesn't really apply anymore"

**Comment by Connoropolous** [comment]
holochain.org is a separate entity from that which I maintain, and I believe that a website refresh is in the works by Klaye. Worth looking into

The Holochain FAQ however I think is updated. If a link can be provided to where it's not...

**Comment by Connoropolous** [comment]
Change requests for the website can be made through the form in the Websites channel of the Mattermost too though

**Comment by Connoropolous** [comment]
It's good this got instigated, it missed our attention. I have submitted a pull request here to update the JS/Lisp thing
https://github.com/holochain/website/pull/70

I will also be exploring further minor updates needing to be made to the site

**Comment by dhtnetwork** [comment]
Per holochain/website#70, this issue has been resolved.
