### ISSUE TITLE
zsh doesn't import nix-shell env vars

### ISSUE THREAD

**Issue by freesig** [holochain/docs-pages#124]
Work around is to add:
`. $HOME/.nix-profile/etc/profile.d/nix.sh` to `~/.zshrc`.

**Comment by freesig** [comment]
nix no longer adding this to bash either

**Comment by syzer** [comment]
same is for Fish shell

**Comment by pdaoust** [comment]
I can confirm this for fish as well. A solution is to:

1. Install [oh-my-fish](https://github.com/oh-my-fish/oh-my-fish).
2. Install [foreign-env](https://github.com/oh-my-fish/plugin-foreign-env): `omf install foreign-env`
3. Add the nix profile to the fish config: `echo "fenv source $HOME/.nix-profile/etc/profile.d/nix.sh" > ~/.config/fish/config.fish`

**Comment by pdaoust** [comment]
Closing and adding a personal to-do to add some zsh and fish content to the advanced install instructions.
