### ISSUE TITLE
"Method not found". I'm doing "app/zome/method" format calls.  All the doc pages regarding frontend interfaces are blank

### ISSUE THREAD

**Issue by dhtnetwork** [holochain/docs-pages#13]
Jimmy, [20 Jan 2019 19:28:50]:
...just dropped into the MatterMost chat, so we'll see there. Basically did the hc-rust todo list tutorial, got it running on a websocket server, but every call I make to it aside from "info/instances" returns "Method not found". I'm doing "app/zome/method" format calls.

and I was curious if any webhook RPC calls are documented anywhere aside from info/instances.

All the doc pages regarding frontend interfaces are blank

Though I know it's early in the process. I just assume they haven't been written yet.

Very early in the process myself, but so far it's not bad. It somewhat stinks that they changed to Rust/WebAssembly recently and invalidated most of the existing tutorials/sample apps in the process, but I understand the move, and ultimately it'll provide greater flexibility in the future. So I'm simultaneously having to learn Rust compared to other widely used languages. Though I think the design of the HC and the use of sharded DHTs and app specific crypto chains is a very cool concept.

**Comment by zippy** [comment]
The method not found usually comes from not having passed in the correct
instance name as is configured in the container config file.

**Comment by Compy** [comment]
@zippy 
Thanks a ton for the response!

Here is the response to the info/instances websocket RPC call
`"[{"id":"test-instance","dna":"hc-run-dna","agent":"hc-run-agent","storage":{"type":"memory"},"network":"{\"backend_kind\":\"MOCK\",\"backend_config\":{\"networkName\":\"mock@cmd/cli/run\"}}"}]"`

I am using the following code from the example TO-DO list:
`function getInstance(info, dna, agent) {
      const entry = Object.entries(info)
        .find(([id, value]) => value.dna === dna && value.agent === agent)
      if (entry) {
        return entry[1].id
      } else {
        return null
      }
    }`

It is called in this context:
`// First, get instance info...
call('info/instances')().then(info => {
  // Now that we have instance info, we can make zome calls by DNA hash (and agent ID)
  // as specified in our container config
  const instance = getInstance(info, 'hc-run-dna', 'hc-run-agent')
  const content = document.querySelector('#message').value

  // Make another zome call now
  call(instance, 'lists', 'main', 'test')({
	list: { name: content }
   })
})`

Not sure why it didn't work until I forced the getInstance function to just return "test-instance".

Got it going, but I'm not sure the tutorial code works out of the box! Again, many thanks. I'll poke around!

**Comment by Connoropolous** [comment]
I will double check the tutorial for what you shared. Glad you have it working now

**Comment by Connoropolous** [comment]
@Compy can you please link me to the place where you got the "following code from the example TO-DO list"

**Comment by dhtnetwork** [comment]
@Compy Closing this item. Feel free to open another issue if we should address further.
