### ISSUE TITLE
Catalina

### ISSUE THREAD

**Issue by freesig** [holochain/docs-pages#149]
I'm opening this issue to investigate getting nix-shell to work on catalina. So far I can't find a working solution. It's not working for @dhtnetwork

**Comment by freesig** [comment]
Potential solutions https://discourse.nixos.org/t/current-status-of-nix-on-macos-catalina/4286/6

**Comment by maxnachamkin** [comment]
@freesig 

Try this.

https://github.com/NixOS/nix/issues/2925#issuecomment-564493970

**Comment by erlend-sh** [comment]
Should eventually be fixed by https://github.com/NixOS/nix/pull/3212

**Comment by dhtnetwork** [comment]
Yay, this has been resolved! Thank you for your help @freesig!! To resolve this issue, please check out these instructions: https://github.com/NixOS/nix/issues/2925#issuecomment-539570232
