### ISSUE TITLE
Suggesting Edit: Hello Gui Tutorial

### ISSUE THREAD

**Issue by rlkelly** [holochain/docs-pages#151]
Page URL: http://developer.holochain.org/docs/tutorials/coreconcepts/hello_gui/

When you say:
```
python -m SimpleHTTPServer

Or if you use Python 3, use this command instead:

python -m http.server
```

I think you can safely remove the python 2 recommendation because it is now deprecated.

**Comment by freesig** [comment]
Yeh I debated this but a lot of systems still have python 2 installed by default. I think I should change the python 3 to the suggested way though and only briefly mention the python 2 way

**Comment by rlkelly** [comment]
It will most likely be python2 by default on all macbooks.  Really depends on what the target user is.

**Comment by pdaoust** [comment]
Closing because we now use `hc run` to serve up the UI instead.
