### ISSUE TITLE
Suggesting Edit: Hello Me Tutorial

### ISSUE THREAD

**Issue by mitra42** [holochain/docs-pages#153]
Page URL: http://developer.holochain.org/docs/tutorials/coreconcepts/hello_me/

Test code says
```
sim2h_url: 'wss://0.0.0.0:9001',
```
But the server is run on 9000
```
sim2h_server -p 9000
```

**Comment by mitra42** [comment]
@dhtnetwork - here's the screen shot to show the example above. Note to a holo coding newbie, I didn't realize that 9001 was a typo and had to match the line below, (there are quite a few p2p servers that work on a number of ports) 
![Untitled](https://user-images.githubusercontent.com/2242709/70978686-56ea4180-2104-11ea-8795-03b6bb30875d.png)

**Comment by freesig** [comment]
This is fixed in the latest release
