### ISSUE TITLE
Suggesting Edit: Hello Me Tutorial - python call needs update

### ISSUE THREAD

**Issue by mitra42** [holochain/docs-pages#160]
Page URL: http://developer.holochain.org/docs/tutorials/coreconcepts/hello_me/

Suggest changing the python invokation line from
```
python -m SimpleHTTPServer
```
to 

```
python -m SimpleHTTPServer
```
Or if you use Python 3, use this command instead:
```
python -m http.server
```
(this is what you have in one of the other tutorials and works)

**Comment by pdaoust** [comment]
closing because we're using `hc run` now instead of `SimpleHTTPServer`.
