### ISSUE TITLE
Suggesting Edit: Hello Me Tutorial - bug in call to show_output ?

### ISSUE THREAD

**Issue by mitra42** [holochain/docs-pages#161]
Page URL: http://developer.holochain.org/docs/tutorials/coreconcepts/hello_me/

This block looks wrong to me ...
```
function hello() {
  holochain_connection.then(({callZome, close}) => {
    callZome('test-instance', 'hello', 'hello_holo')({args: {}}).then(result =>
-      show_output(result),
+      show_output(result, id),
    );
  });
}
```
shouldn't `id` be `output` which is what the element to hold the output of the Hello call is called?

**Comment by freesig** [comment]
This is also fixed by the new releasse
