### ISSUE TITLE
Suggesting Edit: Hello Me Tutorial - Check your code discrepancies in another box

### ISSUE THREAD

**Issue by mitra42** [holochain/docs-pages#162]
Page URL: http://developer.holochain.org/docs/tutorials/coreconcepts/hello_me/

The Check your Code box after the definition of `show_person` is also wrong (seperate box from the error reported in #154 

Specifically - the show_output in the code constructed line by line is ...
```
function show_output(result, id) {
  var el = document.getElementById(id);
  var output = JSON.parse(result);
  el.textContent = ' ' + output.Ok;
}
```
But in the "Check your code box" its 
```
// Render functions
function show_output(result, id) {
  var el = document.getElementById(id);
  var output = JSON.parse(result);
  if (output.Ok) {
    el.textContent = ' ' + output.Ok;
  } else {
    alert(output.Err.Internal);
  }
}
```
With extra error checking ...

**Comment by mitra42** [comment]
Note that box is obviously nonsense as it contains a duplicate `show_person` function. There might be other discrepancies.

**Comment by freesig** [comment]
This is fixed in the current release :smiley:
