### ISSUE TITLE
Suggesting Edit: CRUD Operations

### ISSUE THREAD

**Issue by emalinus** [holochain/docs-pages#164]
Page URL: http://developer.holochain.org/docs/concepts/6_modifying_and_deleting_data/

Hi! The fourth heading, "simulating immutability", should be "simulating mutability".

**Comment by freesig** [comment]
@pdaoust

**Comment by pdaoust** [comment]
Dang, thanks for catching that @emalinus ! changes the meaning of that sentence somewhat, doesn't it? :sweat_smile:

**Comment by pdaoust** [comment]
Fixed in `develop` and will merge to `master` soon.
