### ISSUE TITLE
Suggesting Edit: Hello World Tutorial - sim2h 9000 or 9001

### ISSUE THREAD

**Issue by mitra42** [holochain/docs-pages#167]
Page URL: http://developer.holochain.org/docs/tutorials/coreconcepts/hello_world/

Which port should sim2h run on - consistently the "Check your code" examples are showing `sim2h_url: 'wss://0.0.0.0:9001',` and the page descriptions are saying `sim2h_server -p 9000`

Am I right in assuming this is a typo (examples seem to fail unless this is aligned), and if so which is correct ?

**Comment by freesig** [comment]
This has been fixed now, thanks for the find
