### ISSUE TITLE
Suggesting Edit: Hello World Tutorial - where is bob ? 

### ISSUE THREAD

**Issue by mitra42** [holochain/docs-pages#168]
Page URL: http://developer.holochain.org/docs/tutorials/coreconcepts/hello_world/

Reading the tutorial ... 
```
const bob_retrieve_result = await bob.call('cc_tuts', 'hello', 'retrieve_person', {'address': alice_person_address });
```
Won't work because `bob` isnt declared, comparing the tutorial with the `check your code` looks like you missed telling us to change:
```
  const { alice } = await s.players({alice: config}, true)
```
to
```
  const { alice, bob } = await s.players({alice: config, bob: config}, true)
```

**Comment by mitra42** [comment]
Oh ... and and `Check code` has another `await s.consistency()` after `t.deepEqual(result, { Ok: 'Hello Holo' })`

**Comment by freesig** [comment]
These are both fixed now
