### ISSUE TITLE
Suggesting Edit: Hello World Tutorial - multi terminal test fails with hash issue

### ISSUE THREAD

**Issue by mitra42** [holochain/docs-pages#169]
Page URL: http://developer.holochain.org/docs/tutorials/coreconcepts/hello_world/
Got stuck at this one.

The hash in conductor-config-alice.toml matches the one that `hc hash` returns, but `holochain -c conductor-config-alice.toml` has a completely different idea of what the hash is. and fails 

```
hc hash
starting .bashrc
Reading DNA from /Users/mitra/holo/core_concepts/cc_tuts/dist/cc_tuts.dna.json
DNA Hash: QmaohgPhY4mhCyCiDzw16ZAcXkcpfibzD6unK1GJAXTX2k

[nix-shell:~/holo/core_concepts/cc_tuts]$ grep hash *alice.toml 
hash = 'QmaohgPhY4mhCyCiDzw16ZAcXkcpfibzD6unK1GJAXTX2k'

[nix-shell:~/holo/core_concepts/cc_tuts]$ holochain -c conductor-config-alice.toml
starting .bashrc
Using config path: conductor-config-alice.toml
Reading DNA from dist/cc_tuts.dna.json
Unlocking agent keys:
Unlocking key for agent 'bob': 
conductor: boot_from_config
Reading DNA from dist/cc_tuts.dna.json
Reading DNA from dist/cc_tuts.dna.json
conductor: build_conductor_api instance_id=test-instance, config=Configuration { agents: [AgentConfiguration { id: "bob", name: "Bob", public_address: "HcSCi6q54V833PVHd9mckeY33vCHeymwm7wnkM5UwKGnbijrC38eV3FOqqmb7za", keystore_file: "bob.key", holo_remote_key: None, test_agent: Some(true) }], dnas: [DnaConfiguration { id: "hc-run-dna", file: "dist/cc_tuts.dna.json", hash: "QmaohgPhY4mhCyCiDzw16ZAcXkcpfibzD6unK1GJAXTX2k", uuid: None }], instances: [InstanceConfiguration { id: "test-instance", dna: "hc-run-dna", agent: "bob", storage: Memory }], interfaces: [InterfaceConfiguration { id: "websocket-interface", driver: Websocket { port: 3402 }, admin: true, instances: [InstanceReferenceConfiguration { id: "test-instance", alias: None }] }], bridges: [], ui_bundles: [], ui_interfaces: [], logger: LoggerConfiguration { logger_level: "debug", rules: LogRules { rules: [LogRule { pattern: .*, exclude: true, color: None }, LogRule { pattern: ^lib3h, exclude: false, color: None }, LogRule { pattern: ^holochain, exclude: false, color: None }, LogRule { pattern: ^lib3h, exclude: false, color: None }] }, state_dump: false }, network: Some(Sim2h(Sim2hConfig { sim2h_url: "wss://localhost:9000" })), persistence_dir: "/Users/mitra/Library/Preferences/org.holochain.holochain/conductor", signing_service_uri: None, encryption_service_uri: None, decryption_service_uri: None, dpki: None, signals: SignalConfig { trace: false, consistency: false }, passphrase_service: Cmd, metric_publisher: None }
Reading DNA from dist/cc_tuts.dna.json
Reading DNA from dist/cc_tuts.dna.json
Error while trying to boot from config: ErrorGeneric("Error while trying to create instance \"test-instance\": Provided DNA hash does not match actual DNA hash! QmaohgPhY4mhCyCiDzw16ZAcXkcpfibzD6unK1GJAXTX2k != QmVo8YjB2SqbHF1G2ub2FrxWnDE2LwuHRh9XtKqKHXcVKK")
```

**Comment by mitra42** [comment]
Happy to help debug this if there is interest, but otherwise this is blocking on doing that tutorial.

**Comment by freesig** [comment]
Yep this is a bug in the version of holochain that nix-shell https://holochain.love is pointing to. It's fixed in a more recent version that we will point .love to hopefully today once a MacOS bug is fixed. If you don't want to wait you can point to:
nix-shell https://github.com/holochain/holonix/archive/v0.0.60.tar.gz

**Comment by mitra42** [comment]
Looks like .love is still on 0.0.47 or am I misreading something ?

**Comment by mitra42** [comment]
Reason I'm asking is that your suggestion above doesn't work (at least for me) it reports
```
nix-shell https://github.com/holochain/holonix/archive/v0.0.60.tar.gz
unpacking 'https://github.com/holochain/holonix/archive/v0.0.60.tar.gz'...
unpacking 'https://github.com/mozilla/nixpkgs-mozilla/archive/d46240e8755d91bc36c0c38621af72bf5c489e13.tar.gz'...
error: assertion failed at /nix/store/h8yv9z8l0fqfbas6wdwy7lzagnpwqg3v-source/pkgs/os-specific/linux/kernel/generic.nix:56:1
(use '--show-trace' to show detailed location information)
```

**Comment by freesig** [comment]
ah that should also be fixed now aswell. holochain.love has been updated. Feel free to reopen if you still have the issue.

**Comment by mitra42** [comment]
@freesig I don't have permissions to Reopen this - should I start a new issue ? 

This is far from fixed, I ran down through Hello World again, just as a Check, I tried comparing to the code in the Check box and there were massive differences to what I'd created by accurately following the tutorials up to this point, I don't know if thats part of the WIP stuff, but its sure confusing. 

More importantly - the code (the version from your Check box) fails the single box test badly ... 
```
    Finished release [optimized] target(s) in 16m 13s
> wasm-gc target/wasm32-unknown-unknown/release/hello.wasm
"wasm-gc target/wasm32-unknown-unknown/release/hello.wasm"
starting .bashrc
> wasm-opt -Oz --vacuum target/wasm32-unknown-unknown/release/hello.wasm
"wasm-opt -Oz --vacuum target/wasm32-unknown-unknown/release/hello.wasm"
starting .bashrc
(no output file specified, not emitting output)
> wasm2wat target/wasm32-unknown-unknown/release/hello.wasm -o target/wasm32-unknown-unknown/release/hello.wat
"wasm2wat target/wasm32-unknown-unknown/release/hello.wasm -o target/wasm32-unknown-unknown/release/hello.wat"
starting .bashrc
> wat2wasm target/wasm32-unknown-unknown/release/hello.wat -o target/wasm32-unknown-unknown/release/hello.wasm
"wat2wasm target/wasm32-unknown-unknown/release/hello.wat -o target/wasm32-unknown-unknown/release/hello.wasm"
starting .bashrc
Error: Couldn't traverse DNA in directory "/Users/mitra/holo/core_concepts/cc_tuts": artifact path /Users/mitra/holo/core_concepts/cc_tuts/zomes/hello/code/starting .bashrc
target/wasm32-unknown-unknown/release/hello.wasm either doesn't point to a file or doesn't exist
```
This might be the issue mentioned in https://forum.holochain.org/t/couldnt-traverse-dna-in-directory-with-nix-shell-https-holochain-love/1647/10 but its not clear if its the same problem (and yes, I am on a Mac, and its Mojave (not Cordova)).

Switching back to the code I'd built going through the tutorial hit the same bug. 

Obviously going through the tutorials one by one isn't going to come to the correct set of files, so could you post a complete set of the files for the Hello-World tutorial somewhere so we can check against known working code ?

**Comment by freesig** [comment]
Hi @mitra42 yes this is the same bug.
You will need to update the .hcbuild file under`zomes/hello/code/.hcbuild`. To:
```json
{
  "steps": [
    {
      "command": "CARGO_TARGET_DIR=${CARGO_TARGET_DIR:-/tmp/my_first_app/target} && echo $CARGO_TARGET_DIR",
      "arguments": []
    },
    {
      "command": "CARGO_TARGET_DIR=${CARGO_TARGET_DIR:-/tmp/my_first_app/target} && cargo",
      "arguments": [
        "build",
        "--release",
        "--target=wasm32-unknown-unknown",
        "--target-dir=$CARGO_TARGET_DIR"
      ]
    },
    {
      "command": "CARGO_TARGET_DIR=${CARGO_TARGET_DIR:-/tmp/my_first_app/target} && wasm-gc",
      "arguments": ["$CARGO_TARGET_DIR/wasm32-unknown-unknown/release/hello.wasm"]
    },
    {
      "command": "CARGO_TARGET_DIR=${CARGO_TARGET_DIR:-/tmp/my_first_app/target} && wasm-opt",
      "arguments": [
        "-Oz",
        "--vacuum",
        "$CARGO_TARGET_DIR/wasm32-unknown-unknown/release/hello.wasm"
      ]
    },
    {
      "command": "CARGO_TARGET_DIR=${CARGO_TARGET_DIR:-/tmp/my_first_app/target} && wasm2wat",
      "arguments": [
        "$CARGO_TARGET_DIR/wasm32-unknown-unknown/release/hello.wasm",
        "-o",
        "$CARGO_TARGET_DIR/wasm32-unknown-unknown/release/hello.wat"
      ]
    },
    {
      "command": "CARGO_TARGET_DIR=${CARGO_TARGET_DIR:-/tmp/my_first_app/target} && wat2wasm",
      "arguments": [
        "$CARGO_TARGET_DIR/wasm32-unknown-unknown/release/hello.wat",
        "-o",
        "$CARGO_TARGET_DIR/wasm32-unknown-unknown/release/hello.wasm"
      ]
    }
  ],
  "artifact": "${CARGO_TARGET_DIR:-/tmp/my_first_app/target}/wasm32-unknown-unknown/release/hello.wasm"
}
```

The "check your code" sections are generated from the steps in the tutorial. I had to update some of the steps to fix some issues so they have actually changed.

I don't have the files anywhere because the tutorials are the source code for the tutorials.  I could generate a full set of the files at the end of each tutorial if that would help?

I'll also fix the permissions so you can reopen issues.

**Comment by freesig** [comment]
actually apparently it's not possible to change the permissions for reopening because github doesn't allow it which is unfortunate.

**Comment by mitra42** [comment]
I think you can reopen it !

**Comment by mitra42** [comment]
A complete working reference set of the tutorials I think is crucial given how repeatedly broken they are, and the fluidity and changeability of holochain itself at this stage of its development. 

With a reference set (which is common for other tutorials I've taken), we could at list grab that and confirm that works and then compare the files with the ones built painstakingly step by step to try and undertand how the steps we've just been taught are no longer valid

**Comment by freesig** [comment]
The `hc hash` isssue is no longer a problem so I won't reopen this issue but continue this discussion in  https://github.com/holochain/docs-pages/issues/179
