### ISSUE TITLE
Suggesting Edit: Hello Gui Tutorial

### ISSUE THREAD

**Issue by TinfoilBat** [holochain/docs-pages#170]
Page URL: http://developer.holochain.org/docs/tutorials/coreconcepts/hello_gui/

Hi, simply pointing out that in the previous tutorial (Holo Test) you specify the server commands for python2 and python3. In the Holo GUI only the python2 command is specified.

For all the n00bs out there (like me).

**Comment by freesig** [comment]
python will be going away in our next release but that's for the tip

**Comment by freesig** [comment]
python is removed now
