### ISSUE TITLE
Suggesting Edit: Hello Gui Tutorial 2

### ISSUE THREAD

**Issue by TinfoilBat** [holochain/docs-pages#171]
Page URL: http://developer.holochain.org/docs/tutorials/coreconcepts/hello_gui/

Oh, and I don't know if it's here or the previous test, but there is one extra (or missing) 's' on the
```javascript
      var holochain_connection = holochainclient.connect({
        url: 'ws://localhost:3401',
      });
```
part.

I don't know if the above is correct, but on the previous tutorial, there is 'wss://'...  written somewhere. Some of the two must be wrong, I guess.

Cheers,

**Comment by freesig** [comment]
Thanks for finding this @TinfoilBat We are in the process of switching to using a bundle.toml file to specify this. I'm hoping to get this out by tomorrow then you won't need to specify this at all :)

**Comment by freesig** [comment]
This is fixed now
