### ISSUE TITLE
Suggesting Edit: Hello World Tutorial

### ISSUE THREAD

**Issue by kalisam** [holochain/docs-pages#178]
Page URL: http://developer.holochain.org/docs/tutorials/coreconcepts/hello_world/

I think the command for making an agent named bob should be set to Bob, when its currently set to Alice, just a small typo

```
Terminal three¶
Start the second conductor with agent name set toBob:

Run in nix-shell https://holochain.love

hc package
hc run --networked sim2h --agent-name Alice
```

**Comment by mitra42** [comment]
@kalisam - looks like the bug's more complex, I tried the fix suggested in https://github.com/holochain/docs-pages/issues/187 which worked for me - seems like there is noone left at Holo checking this forum :-(

**Comment by pdaoust** [comment]
@kalisam thanks for your keen eye. Someone's submitted a pull request (#186) to resolve this issue; I'll track it over there.
