### ISSUE TITLE
Suggesting Edit: Hello World Tutorial

### ISSUE THREAD

**Issue by DrewMcArthur** [holochain/docs-pages#183]
https://developer.holochain.org/docs/tutorials/coreconcepts/hello_world/#terminal-three

Comment says:
"Start the second conductor with agent name set to Bob:"

But the example code says:
`hc run --networked sim2h --agent-name Alice`

**Comment by DrewMcArthur** [comment]
example code should be:
`hc run --networked sim2h --agent-name Bob --port 8889`

**Comment by pdaoust** [comment]
Hey @DrewMcArthur thanks very much for your astute eyes. Closing this one as it's resolved in #186 .
