### ISSUE TITLE
Suggesting Edit: Hello World Tutorial

### ISSUE THREAD

**Issue by friedger** [holochain/docs-pages#185]
Page URL: http://developer.holochain.org/docs/tutorials/coreconcepts/hello_world/

At the end when opening Terminal 3, the agent is called again `Alice` instead of `Bob`

**Comment by mitra42** [comment]
Seems to be related to https://github.com/holochain/docs-pages/issues/187 which has a suggested fix to the bug

**Comment by pdaoust** [comment]
Closing as a duplicate of #187.
