### ISSUE TITLE
Suggesting Edit: Hello World Tutorial

### ISSUE THREAD

**Issue by Chris39704** [holochain/docs-pages#187]
Page URL: http://developer.holochain.org/docs/tutorials/coreconcepts/hello_world/

Terminal 3:
hc package
hc run --networked sim2h --agent-name Bob --port 8889

currently the suggested code is duplicated from Terminal 2 and when run with Agent bob the conductor will error out with port 8888 already in use unless 8889 is specified.

Thanks!

**Comment by mitra42** [comment]
Thanks @Chris39704 - I think the bug I posted is the same. 

@pdaoust - someone said recently they'd run all the tutorials and they all worked, seems unlikely given all the pretty obvious bugs in them.

**Comment by pdaoust** [comment]
@mitra42 you may be right -- possibly "worked" meant "caught the typos and fixed them". Will keep this issue open as it's the most complete solution. Thanks for reporting @Chris39704 !

**Comment by pdaoust** [comment]
Additional comment: On the same page, where it directs the user to go to Bob's UI, the URL should have `:8889` in it rather than `:8888`. See #191 for details.

**Comment by pdaoust** [comment]
I've discovered PR #186 which aims to correct this issue; I've requested that they add the explicit port number `8889` to the change. Once that's happened, I'll merge and close!
