### ISSUE TITLE
Suggesting Edit: Validate Agent

### ISSUE THREAD

**Issue by DrewMcArthur** [holochain/docs-pages#192]
Page URL: http://developer.holochain.org/docs/guide/zome/validate_agent/

can we also have a guide page for a sample validation? for example, i'm trying to check if a user entry already exists (separate from the agent, to have one holochain node support multiple users).  it would be helpful to have some sample entry validation code.

**Comment by pdaoust** [comment]
Hi @DrewMcArthur thanks for the feedback! We definitely need more sample code in the HDK docs -- and a lot of other documentation too. Rest assured that this is on our to-do list.

To your specific use case, may I ask what the scenario is that requires a node to support multiple users? One of the core design principles of Holochain is that user = agent = human, to allow them to have exclusive control over their own source chain.

**Comment by DrewMcArthur** [comment]
thanks for all the replies @pdaoust !  the use case i have in mind is a web app with a single server that serves a website to multiple users, and passes database calls back to multiple holochain nodes acting as the backend.  it would be a traditional client-server-db app, but allowing anyone that's part of the app to help host the database, and easily allow for scalability.

**Comment by pdaoust** [comment]
If my understanding of your use case is correct, that overlaps nicely with the use case of Holo Host -- have you checked it out?

I can distinguish certain differences -- for example, I'm guessing you want traditional logins, where the `user` entry type is just a username and password hash stored on the DHT, right?

My chief concern here is that this design might be working against the grain of Holochain's intended use case, and that could cause you all sorts of frustration. It also might be incompatible with the terms of the Cryptographic Autonomy License, which is soon to be Holochain's official license. But IANAL, so I'm double-checking on this right now.

**Comment by pdaoust** [comment]
I'm still trying to parse the [CAL](https://github.com/holochain/cryptographic-autonomy-license), but there's a 'performance' clause that makes it work somewhat like the [Affero GPL](https://www.gnu.org/licenses/agpl-3.0.en.html), in that it applies even to server-hosted software. My reading is that this would mean that you'd have to make all user data available to users in a way that lets them reuse the data in their own copy of the software. The easiest way to do that would be to let them create their own keys and let them download their own source chains, which implies one hosted instance per user. That's probably not the _only_ way to do it, but I think you'd be working hard to come up with patterns that make it possible some other way.

So, to be clear, this app would be a mix of Holochain-native users and web-hosted, and you want to take advantage of Holochain for elasticity? I wonder if there are other designs that would support user agency more directly. Every idea I have keeps coming back to Holo Host though :sweat_smile:

**Comment by pdaoust** [comment]
Closing
