### ISSUE TITLE
Suggesting Edit: Hello Gui Tutorial

### ISSUE THREAD

**Issue by Joshfairhead** [holochain/docs-pages#199]
Page URL: http://developer.holochain.org/docs/tutorials/coreconcepts/hello_gui/

The naming convention between pages is inconsistent. On hello holo tutorial the suggested root directory is "coreconcepts". In this tutorial its "cd ~/holochain/core_concepts"

While perhaps obvious that the underscore will need removing it maybe creates unnecessary friction as an underscore will need removing.

**Comment by freesig** [comment]
Thanks :)
