### ISSUE TITLE
Suggesting Edit: Hello Gui Tutorial

### ISSUE THREAD

**Issue by Joshfairhead** [holochain/docs-pages#200]
Page URL: http://developer.holochain.org/docs/tutorials/coreconcepts/hello_gui/

This instruction seems to be wrong?
"Add this water.css link inside the `<head>` tag:"

Then checking the code block its stored below the /head in the body... I'd paste the code below but larger code blocks on Github seems not to be working for me (n00b)... please see the solution box to see what I mean

**Comment by freesig** [comment]
Thanks yep I'll change it to inside the head now.
