### ISSUE TITLE
Suggesting Edit: CRUD Operations

### ISSUE THREAD

**Issue by bierlingm** [holochain/docs-pages#207]
Page URL: http://developer.holochain.org/docs/concepts/6_modifying_and_deleting_data/

In the first sentence of [this section](https://developer.holochain.org/docs/concepts/6_modifying_and_deleting_data/#handling-privacy-concerns-and-storage-constraints), sentence #2, word #3 should be `ask`, not `asks`.

**Comment by pdaoust** [comment]
Hi, Moritz. Cleaning up old suggestions and closing -- rewrote the Core Concepts and probably caught this typo. Thanks for reporting!
