### ISSUE TITLE
Suggesting Edit: Hello Me Tutorial - Inconsistency

### ISSUE THREAD

**Issue by Joshfairhead** [holochain/docs-pages#212]
Page URL: http://developer.holochain.org/docs/tutorials/coreconcepts/hello_me/

In the section
`  #[zome_fn("hc_public")]
  pub fn hello_holo() -> ZomeApiResult<String> {
      Ok("Hello Holo".into())
  }`

The function is public. In the check your code part there is no `pub` section just `fn hello_holo`

I imagine that functions that are not explicitly private default to public anyway, however its still useful for n00bs like me to have consistent docs as I probably shouldn't be making assumptions at this stage of my self-education

**Comment by pdaoust** [comment]
Thanks for catching that. I'm closing, as we've removed all the tutorials from the dev docs website in order to have no old legacy HC-Redux-specific content.
