### ISSUE TITLE
Suggesting Edit: Hello Me Tutorial - inaccurate code block

### ISSUE THREAD

**Issue by Joshfairhead** [holochain/docs-pages#213]
Page URL: http://developer.holochain.org/docs/tutorials/coreconcepts/hello_me/

Hey again, at the GUI section the instructions say "Look for the previous ‘say hello’ elements."
`    <button onclick="hello()" type="button">Say Hello</button>
    <div>Response:</span><span id="output"></div>
    `

When in fact the code looks like
`<button onclick="hello()" type="button">Say Hello</button>
      <script
      type="text/javascript"
      src="hc-web-client/hc-web-client-0.5.1.browser.min.js"
      ></script>
      <script type="text/javascript" src="hello.js"></script>
      <div>Response: <span id="output"></span></div>`

I've made some jumps that it goes under the `<div>Response: <span id="output"></span></div>` section but for clarity we might include the whole block - I'm a n00b and probably shouldn't have to make assumptions (unless of course my code is wrong, in which case I just incorrectly made one)

**Comment by Joshfairhead** [comment]
Actually getting down the page a bit further the script section in my code is early (compared to yours), at the bottom of the check your code section its still there in the documentation. 

My script section however is an inheritance from earlier tutorials... perhaps theres something to go back and check there... or I just got it wrong earlier and everything passed fine!

**Comment by pdaoust** [comment]
Thanks for catching that. I'm closing, as we've removed all the tutorials from the dev docs website in order to have no old legacy HC-Redux-specific content.
