### ISSUE TITLE
Suggesting Edit: Create a New App

### ISSUE THREAD

**Issue by mhuesch** [holochain/docs-pages#215]
Page URL: http://developer.holochain.org/docs/create-new-app/

> Run a Holochain conductor
> You will need to create a config file. See the hello_world tutorial for an example.

The `hello_world` link is broken for me.

**Comment by pdaoust** [comment]
Thanks for catching that. I'm closing, as we've removed the entire Guidebook from the dev docs website in order to have no old legacy HC-Redux-specific content.
