### ISSUE TITLE
Suggesting Edit: Writing a Development Kit (HDK'

### ISSUE THREAD

**Issue by mhuesch** [holochain/docs-pages#216]
Page URL: http://developer.holochain.org/docs/guide/writing_development_kit/

> While it is possible to look at the Rust language HDK as a reference

Broken link. I think it should point to https://github.com/holochain/holochain-rust/tree/develop/crates/hdk_v2.

**Comment by pdaoust** [comment]
Thanks for catching that. I'm closing, as we've removed the entire Guidebook from the dev docs website in order to have no old legacy HC-Redux-specific content.
