### ISSUE TITLE
Suggesting Edit: Hello World Tutorial

### ISSUE THREAD

**Issue by Joshfairhead** [holochain/docs-pages#217]
Page URL: http://developer.holochain.org/docs/tutorials/coreconcepts/hello_world/

Biiiiiiiiiiiiiiiiiigggggg space below "Make your entry public section" - or before "add bob to the test" header

**Comment by pdaoust** [comment]
Thanks for catching that -- and I'm sorry I didn't see this before. I'm closing, as we've removed all the tutorials from the dev docs website in order to have no old legacy HC-Redux-specific content.
