### ISSUE TITLE
Zome doesn't compile when following Hello Holo Tutorial

### ISSUE THREAD

**Issue by bierlingm** [holochain/docs-pages#222]
**Describe the bug**
I followed the [Hello Holo Tutorial](https://developer.holochain.org/docs/tutorials/coreconcepts/hello_holo/) up until the point of generating a zome. But when I run `hc package`, I get a failing build message:

```
error[E0433]: failed to resolve: could not find `document_join_macro` in `futures_util`
   --> /Users/moritzbierling/dev/p2p/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.3.2/src/lib.rs:561:15
    |
561 | futures_util::document_join_macro! {
    |               ^^^^^^^^^^^^^^^^^^^ could not find `document_join_macro` in `futures_util`

error[E0433]: failed to resolve: could not find `document_select_macro` in `futures_util`
   --> /Users/moritzbierling/dev/p2p/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.3.2/src/lib.rs:584:15
    |
584 | futures_util::document_select_macro! {
    |               ^^^^^^^^^^^^^^^^^^^^^ could not find `document_select_macro` in `futures_util`

error: aborting due to 2 previous errors

For more information about this error, try `rustc --explain E0433`.
error: could not compile `futures`.
warning: build failed, waiting for other jobs to finish...
error: build failed
Error: Couldn't traverse DNA in directory "/Users/moritzbierling/dev/p2p/Holochain/coreconcepts/cc_tuts": command CARGO_TARGET_DIR=${CARGO_TARGET_DIR:-/tmp/my_first_app/target} && cargo build --release --target=wasm32-unknown-unknown --target-dir=$CARGO_TARGET_DIR was not successful
```

**To Reproduce**
1. Go to 'https://developer.holochain.org/docs/tutorials/coreconcepts/hello_holo/'
2. Follow the instructions on the site up until the point of generating a zome.
3. Type `hc package` into your terminal.

**Expected behavior**
I expected the zome to compile without error.

**Screenshots**
<img width="1552" alt="Screen Shot 2020-05-24 at 20 10 03" src="https://user-images.githubusercontent.com/9335771/82761407-91b27d00-9dfa-11ea-8e4e-cdca291e9844.png">

<img width="906" alt="Screen Shot 2020-05-24 at 20 09 20" src="https://user-images.githubusercontent.com/9335771/82761394-7b0c2600-9dfa-11ea-92a4-286021e1eb1a.png">

**Desktop (please complete the following information):**
 - OS: `macOS Catalina 10.15.5 Beta (19F94a)`
 - Holochain version: `holochain 0.0.47-alpha1`
 - HC version: `hc 0.0.47-alpha1`
 - HDK version: `hdk = "=0.0.47-alpha1"`

**Additional context**
/

**Comment by krpone** [comment]
Yes thanks, same thing happened for me too.

**Comment by krpone** [comment]
@bierlingm  This is open somewhere else as well. https://forum.holochain.org/t/compiling-error-with-hello-zome-error-e0433-failed-to-resolve-could-not-find-document-join-macro-in-futures-util/3033

**Comment by pdaoust** [comment]
Thanks for catching that, folks -- and I'm sorry I didn't see this before. I'm closing, as we've removed all the tutorials from the dev docs website in order to have no old legacy HC-Redux-specific content.
