### ISSUE TITLE
Holochain RSM Guidance link is broken

### ISSUE THREAD

**Issue by mhuesch** [holochain/docs-pages#246]
## What is incorrect

banner link is broken. e.g. here: https://developer.holochain.org/docs/concepts/5_linking_data_together/

it should link to https://developer.holochain.org/holochain-rsm-guidance.html, so I am guessing the link is not properly relativized.

**Comment by pdaoust** [comment]
oh gosh, thanks for catching that -- I have to confess I hadn't checked these issues in a while. I'll set up automatic notifications.

As of last Friday, the legacy dev docs have been moved to https://redux.developer.holochain.org, and it looks like the banner works both there and on the refreshed site at https://developer.holochain.org. Thanks for your bug report!!!!!!
