### ISSUE TITLE
Suggesting Edit: Introduction

### ISSUE THREAD

**Issue by Rev-Matt-A-PhD** [holochain/docs-pages#254]
Page URL: http://developer.holochain.org/docs/

**VOTE 1 BUG!**    :microbe: :mosquito: :butterfly: :cricket:

**Comment by pdaoust** [comment]
Hi, Rev Matt, I'm sorry I didn't see this sooner -- TBH I have to confess that I haven't been checking the issues for this repo very fastidiously. What was the error you saw there?

**Comment by Rev-Matt-A-PhD** [comment]
Thanx for reply.  No worries.  I think 'things' have sorted themselves 
out.  Take care, stay safe, cheers from Rev. Matt.

------ Original Message ------
