### ISSUE TITLE
Feedback on new Application Architecture page

### ISSUE THREAD

**Issue by jost-s** [holochain/docs-pages#305]
### What is the URL of the page?
https://developer.holochain.org/concepts/2_application_architecture/

### Feedback
Hi @pdaoust and @Connoropolous,

I find the new page plain brilliant! It was written for me, because a couple of days ago I was perplexed by Holochain's architecture (because of a [question related to agents and Tryorama's players](https://forum.holochain.org/t/tryorama-players-and-agents/6755/7)) and came back to the glossary and this architecture page. But it didn't help me solve the chaos of terms and elements of the architecture. Especially what I was missing was a diagram that ties it all together and I was starting to draw my own.

And now here we have it all! With the text and the illustrations I manage to understand the conceptually subtle differences between zomes and DNA and agents and clients, and get the interplay of these elements. Great structure of the article too, an overview and then the parts and tying it together in the end paints the complete picture.

At first I thought you could number the 6 pieces in the last diagram to correspond to the enumeration that follows, but 1-5 are self-evident and 6 consists of two parts that can be linked to the two remaining drawings, so probably that's not necessary.

What about "slots" I wonder? Does it refer to anything that exists in technical terms? It's not mentioned in the glossary, so is it a term that's commonly used in relation to hApps? If not you could remove it IMO, because it introduces another term.

All in all like I said I find the page a fantastic reference (who makes these great illustrations? 😀) and I'm glad and thankful to have a much better grasp on these essential concepts and particularly for the diagram that contains it all! 🤩

**Comment by Connoropolous** [comment]
Slots yes slots... was a sticking point for us too. 

It is a thing though, but only part way built so thats why it sticks out

https://github.com/holochain/holochain/blob/2d9401a5e0f74934195a0bf02ca198679b53089d/crates/hc_bundle/tests/fixtures/my-app/happ.yaml#L8

**Comment by jost-s** [comment]
@Connoropolous I see, in fact I came across slots now when installing hApps into the conductor. It doesn't seem to be an important concept as it stands now, but it doesn't disturb much the reader's flow either.

**Comment by pdaoust** [comment]
@jost-s thank you a thousand times for taking the time to write this feedback; I really appreciate it. The App Architecture page always felt awkward to me -- it didn't really explain things well, I thought. Connor did the reframing and I rewrote the bit about agent-centricity at the beginning.

I like the idea of numbering the summary diagram too; it probably ought to make it into next round of edits.

**Comment by Connoropolous** [comment]
Agreed, great feedback. By the way, @pdaoust are you aware that @jost-s has undertaken to do some contributing to documentation of his own, as well as some code quality? 

He contributed the typescript based happ-client-call-tutorial https://github.com/holochain/happ-client-call-tutorial/pull/2
after I had posted a 'good-first-issue' label on a TODO that I stuck in the README when it was just Rust. You two should be in touch if you aren't!

**Comment by Connoropolous** [comment]
He also posted a PR to conductor-api that's a code quality thing, but it hasn't been responded to yet. Do you have any means to get that followed up on? https://github.com/holochain/holochain-conductor-api/pull/79

I used to play a bit of a role in that repo, but I've stepped back so I don't consider myself a suitable reviewer

**Comment by Connoropolous** [comment]
A third thing, oops... while we're at it, I humbly suggest happ-client-call-tutorial as a candidate for being in the pinned Holochain org repos, don't know if you'd agree. 
<img width="1229" alt="Screen Shot 2021-09-07 at 3 44 33 PM" src="https://user-images.githubusercontent.com/1409121/132402118-8b81f786-6892-47d3-80d9-22ad77b34a2e.png">

**Comment by jost-s** [comment]
@pdaoust I don't have access to configure the pinned repos. Do you?
