### ISSUE TITLE
lair-keystore should be mentioned as a main binary? 

### ISSUE THREAD

**Issue by Connoropolous** [holochain/docs-pages#333]
https://developer.holochain.org/references/

I think lair-keystore, being so essential, should be mentioned as a main binary here
<img width="790" alt="Screen Shot 2022-09-19 at 9 39 47 AM" src="https://user-images.githubusercontent.com/1409121/191069146-9e68ced7-c244-4657-90c0-b591be1cc862.png">

**Comment by jost-s** [comment]
Agreed.

fix in #341
