### ISSUE TITLE
Error when running scaffolding command from `install.md`

### ISSUE THREAD

**Issue by DrewMcArthur** [holochain/docs-pages#347]
**Describe the bug**
running `nix-shell https://holochain.love --run "hc scaffold example forum"` yields the following error:

```
error: Package ‘webkitgtk-2.38.2+abi=4.0’ in /nix/store/62v5iyzgyk71cp1rbwj2f5mb1lkwirih-source/pkgs/development/libraries/webkitgtk/default.nix:241 is marked as broken, refusing to evaluate.

       a) To temporarily allow broken packages, you can use an environment variable
          for a single invocation of the nix tools.

            $ export NIXPKGS_ALLOW_BROKEN=1

        Note: For `nix shell`, `nix build`, `nix develop` or any other Nix 2.4+
        (Flake) command, `--impure` must be passed in order to read this
        environment variable.

       b) For `nixos-rebuild` you can set
         { nixpkgs.config.allowBroken = true; }
       in configuration.nix to override this.

       c) For `nix-env`, `nix-build`, `nix-shell` or any other Nix command you can add
         { allowBroken = true; }
       to ~/.config/nixpkgs/config.nix.
(use '--show-trace' to show detailed location information)
```

**To Reproduce**
1. Follow install instructions on a clean macOS, installing nix-shell
2. run above scaffolding command
3. maybe see the following error
4. wonder if this is because holochain needs to update to a newer webkitgtk package version, or if the docs should just tell me to choose one of the nix-shell options given in the error message

**Expected behavior**
Either the version required for webkitgtk is updated to a non-broken version, or the install docs tell me which of these three options i should choose.

**Desktop (please complete the following information):**
 - OS: macOS
 - Holochain version `holochain --version`: not yet installed
 - HC version `hc --version` not yet installed
 - HDK version [e.g. inside my_app/zomes/my_zome/code/Cargo.toml `hdk = "0.0.38-alpha14"`] not yet installed

**Additional context**
Also submitted [holonix#1090](https://github.com/holochain/holonix/issues/1090), since i didn't see this repo at first.  not sure where this issue belongs.

**Comment by DrewMcArthur** [comment]
side note, it would be helpful for devs like me to point out where certain pieces' repositories are - my current hunch (i'm not super familiar with nixOS so i could be wrong) is that the tarball package that `nix-shell` fetches from `https://holochain.love` needs to update its version of `webkitgtk`.  If the docs provided some of that extra background information (maybe in the advanced installation docs), and told me where different tools were built from, i could more easily do a little digging for myself.

**Comment by DrewMcArthur** [comment]
currently following option `a)` in the error message, by running `export NIXPKGS_ALLOW_BROKEN=1; nix-shell https://holochain.love`.  seems to be working so far.

**Comment by DrewMcArthur** [comment]
`nix-shell https://holochain.love --run "hc scaffold example forum"`

trying this command again today (without the temporary env variable in the comment above) and it appears to be working! must have been a temporary issue.  i'll leave this open so that somebody on the holochain team sees this, but feel free to close this out!

**Comment by marycamacho** [comment]
Mac was not supported until last week. Closing this issue and will review if any further ones are posted.
