### ISSUE TITLE
Add additional social/community channels/links to the footer

### ISSUE THREAD

**Issue by dhtnetwork** [holochain/docs-pages#4]
Request: 
Page: developer.holochain.org
Add: Mattermost at the top before or after Blog?  
Link: Mattermost: https://chat.holochain.net/appsup/channels/app-dev
Add Telegram: http://t.me/channelHolo 
Add Reddit: https://www.reddit.com/r/holochain/

**Comment by Connoropolous** [comment]
Kk... mattermost and reddit were already there, but telegram is added now :)
