### ISSUE TITLE
Practical docs for Zome Calls

### ISSUE THREAD

**Issue by mattyg** [holochain/docs-pages#469]
Must include:
- code examples
- practical, terse explanation of how to *use*
- gotchas
    

Potentially split into multiple pages

Topics to cover:
* Zome functions and calls
    * `#[hdk_extern]`
    * single parameter
    * return value type
    * short-circuiting fallible functions with `?`
    * Remote calls
    * Cross-zome/cell calls
    * Capabilities
    * Specially supported pattern: fire-and-forget remote signals
    * `post_commit`
        * infallible, read-only, but can `call()` another function
        * Warning against sending signals in a zome call unless you know what you're doing (writes may not succeed)
    * source chain head moved errors

**Comment by pdaoust** [comment]
Broken up into #491, #492, and #493 (with the exception of signals, which I now think we should deal with in a separate article)

**Comment by pdaoust** [comment]
Closing now that it's broken into story-sized chunks.
