### ISSUE TITLE
Practical guide to app architecture

### ISSUE THREAD

**Issue by mattyg** [holochain/docs-pages#480]
Must include:
- code examples
- practical, terse explanation of how to *use*
- gotchas

Topics to cover:

* Composing zomes and DNAs into an app
    * DNA and app manifest formats
    * Coordinator swapping
    * cell provisioning strategies
        * `Create` -- always create a new cell
        * `UseExisting` -- requires existing cell under same key derivation tree (not implemented?)
        * `CreateIfNotExists` -- try `UseExisting` followed by `Create` (not implemented?)
        * `CloneOnly` -- defer instantiation until first clone. How is this different from `Create` with `deferred` and no effective instantiation?
    * Common flags
        * `deferred` -- don't create one until asked (not implemented? how do you ask?)
        * `clone_limit` -- how many clones can be created?

**Comment by pdaoust** [comment]
Broken out into #488, #489, and #490.

**Comment by pdaoust** [comment]
Closing now that it's broken into story-sized chunks.
