### ISSUE TITLE
New docs website: button to edit a page directs to an issue

### ISSUE THREAD

**Issue by jamesray1** [holochain/docs-pages#74]
Steps to reproduce:

1. Go to a docs page, e.g. https://developer.holochain.org/docs/guide/conductors/
2. Click the edit button

I am redirected to a new GitHub issue with a template like so:
![image](https://user-images.githubusercontent.com/16969914/66627136-75384a80-ec46-11e9-9306-cfb97f68ed27.png)

Expected/desired behaviour: to be redirected like on the previous site to be able to edit the source code for the page directly. This is particularly helpful for minor edits, which are not expected to need discussion.

**Comment by dhtnetwork** [comment]
Hi @jamesray1, indeed the intent is to direct the user to submit an issue.  At this point in time, the desired action is not to edit the page directly.  Please note that the guidebook will be revamped.
