### ISSUE TITLE
Suggesting Edit: Install Holochain

### ISSUE THREAD

**Issue by jamesray1** [holochain/docs-pages#79]
Page URL: http://developer.holochain.org/docs/install/

As per https://github.com/holochain/holochain-rust/issues/1760, this page needs a couple of updates IMO.

Firstly, on my computer with Manjaro Linux, I need to pipe `curl https://nixos.org/nix/install` with a shell command, otherwise it doesn't work (see the above issue for details). E.g., as I use zsh by default, I ran `curl https://nixos.org/nix/install | zsh`, other common ones would be piped with `bash` or `sh`.

Secondly, I got:

```
[jr@lm ~]$ nix-env --versioncopy
error: no operation specified
[jr@lm ~]$ nix-env --version
nix-env (Nix) 2.3.1
```

So LTM like it needs to be updated to `nix-env --version`.

**Comment by freesig** [comment]
These are fixed now
