### ISSUE TITLE
Suggesting Edit: Networking

### ISSUE THREAD

**Issue by jamesray1** [holochain/docs-pages#81]
Page URL: http://developer.holochain.org/docs/guide/conductor_networking/

CTRL+F "Must be one of the following: 't', 'd', 'i', 'w', 'e' Each value"

->

This must be one of the following: 't', 'd', 'i', 'w', 'e'. Each value

n3h docs look like they could be improved, but that is too general a suggestion to create an issue for.

**Comment by jamesray1** [comment]
Generally the page sounds a bit terse, sentences could be more complete.

**Comment by dhtnetwork** [comment]
Thanks, please note that the entire guidebook will be revamped. And we will certainly improve the information and sentence structure. It will take some time.

You'll notice we have add the following for the guidebook:
Please Note

We are currently revamping our developer documentation and have plans for a new guidebook. Please feel free to use the current guidebook, but note that it will be replaced in the future.
