### ISSUE TITLE
will docs.rs be used for API documentation when holochain is published to crates.io soon?

### ISSUE THREAD

**Issue by Connoropolous** [holochain/docs-pages#87]
seems recommendable to me, simplifies the work over here

**Comment by freesig** [comment]
That would be ideal. Happy to give it a go.

**Comment by Connoropolous** [comment]
looks like lots of the published crates are already having documention on docs.rs, but notably, some aren't, because the Cargo.toml files point back to Github itself for that documentation, wrongly so.

**Comment by Connoropolous** [comment]
Scanning through the actual links to documentation on this page https://crates.io/search?q=holochain you see how some of them point back to Github and some point to docs.rs?

**Comment by freesig** [comment]
Hmm I'm trying to get this going. The [hdk](https://crates.io/crates/hdk) is on crates but I can't find it on docs.rs

**Comment by freesig** [comment]
Oh wait maybe this is it https://docs.rs/hdk/0.0.37-alpha6/hdk/

**Comment by freesig** [comment]
This is now live in 0.2.1
