### ISSUE TITLE
Suggesting Edit: Install Holochain

### ISSUE THREAD

**Issue by jamesray1** [holochain/docs-pages#88]
Page URL: http://developer.holochain.org/docs/install/

Note that if you will be running `nix-shell https://holochain.love` frequently, you may wish to set an alias, e.g. as instructed on [this page](https://www.hostingadvice.com/how-to/set-command-aliases-linuxubuntudebian/).

```
Note that if you will be running `nix-shell https://holochain.love` frequently, you may wish to set an alias, e.g. as instructed on [this page](https://www.hostingadvice.com/how-to/set-command-aliases-linuxubuntudebian/).
```

**Comment by freesig** [comment]
You should not need to run this command that frequently. The idea is to keep the nix-shell open and run commands in it. 
Just want to make sure that's clear in the docs or should I update them to make sure it is?

**Comment by jamesray1** [comment]
OK I suppose that would work too and then on restarting you can just tap up to access the command you ran previously, where that command would only be run in that terminal. Although, other commands would be run in the nix-shell in that terminal. So IMO having the alias would still be handy. YMMV.
