### ISSUE TITLE
Suggesting Edit: Install Holochain

### ISSUE THREAD

**Issue by m1keg** [holochain/docs-pages#96]
Page URL: http://developer.holochain.org/docs/install/

After the curl command (the next command) requires an update to the environment.  The command line says this can be done by running ~/.nix-profile/etc/profile.d/nix.sh, except after the install this file needs to be chmod +x first.  And this doesn't do it; you need to force the exports, the simplest way is to logout and log in again.

**Comment by adappt-io** [comment]
the command to check correct install is
`nix-env --version`
not
`nix-env --versioncopy` (no such option).

**Comment by freesig** [comment]
Was this just because of the in correct command or is the logout and in still required?

**Comment by adappt-io** [comment]
A number of issues here:  1. nix.sh needs to be an executable (chmod +x)   2. Need an EXPORT to the environment (as mentioned, log out/in is one way, another would be this command with the variables to export as one line in a script)  3. The typo of version vs versioncopy.   Sorry to have combine three in one or have not made this clear.

Please look at the best way to do my point 2.

**Comment by pdaoust** [comment]
Cleaning up old issues, incl ones that may have gotten forgotten. @m1keg Do you still experience these issues when you follow the new updated-for-RSM install guide at the same URL?

**Comment by m1keg** [comment]
No please close this medieval issue.
